services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:16
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - ./data/filestore:/var/lib/odoo/filestore
      #- /usr/lib/python3/dist-packages/odoo/addons:/usr/lib/python3/dist-packages/odoo/addons:ro
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_FILTER=^maquiser_.*$

#services:
#  db:
#    image: postgres:13
#    environment:
#      POSTGRES_USER: odoo
#      POSTGRES_PASSWORD: odoo
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#
#  odoo-init:
#    image: odoo:16
#    depends_on:
#      - db
#    volumes:
#      - ./addons:/mnt/extra-addons
#      - ./config/odoo.conf:/etc/odoo/odoo.conf
#      - ./init:/init
#    entrypoint: ["bash", "/init/init.sh"]
#    environment:
#      - HOST=db
#
#  odoo:
#    image: odoo:16
#    depends_on:
#      - db
#    ports:
#      - "8069:8069"
#    volumes:
#      - ./addons:/mnt/extra-addons
#      - ./config/odoo.conf:/etc/odoo/odoo.conf
#    environment:
#      - HOST=db
#    command: ["odoo"]
#
